#!/bin/bash

#
# This script indents all source files of geotop according to our
# usual code formatting standards. It is used to ensure that our
# code base looks uniform, as uniformity helps make code easier to
# read.
#
# While we're already touching every file, this script also makes
# sure we set permissions correctly
#
# The script needs to be executed as 
#   ./utils/indent
# from the top-level directory of the source tree, or via
#   make indent
# from a build directory.
#

# Author: Alberto Sartori (2018). This script has been adapted from
# the deal.II library (www.deal.II.org)


if test ! -d src -o ! -d tests -o ! -d examples ; then
  echo "*** This script must be run from the top-level directory of the repo."
  exit 1
fi


# collect all header and source files and format them
find examples src tests    \
     \(                    \
     -name '*.cc' -o       \
     -name '*.h'  -o       \
     -name '*.c'           \
     \)                    \
     -exec clang-format -i {} \;

