
long ind_matrix(long r, long c, LONGVECTOR *Ax, LONGVECTOR *Ai);

int mat_lu( DOUBLEVECTOR *Ap, LONGVECTOR *Ax, LONGVECTOR *Ai, LONGVECTOR *P );

void mat_backsubs1(DOUBLEVECTOR *Ap, LONGVECTOR *Ax, LONGVECTOR *Ai, DOUBLEVECTOR *B, DOUBLEVECTOR *X, LONGVECTOR *P);

void mat_lsolve(DOUBLEVECTOR *Ap, LONGVECTOR *Ax, LONGVECTOR *Ai, DOUBLEVECTOR *B, DOUBLEVECTOR *X);